import React, { useState, useEffect } from 'react';
import {
    View,
    Text,
    TouchableOpacity,
    StyleSheet,
    Modal,
    ScrollView,
    TextInput,
    Switch,
    Dimensions,
    ActivityIndicator,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { X, Check, Save } from 'lucide-react-native';
import { colors, gradients } from '@/src/core/constants/Theme';
import { isRTL } from '@/src/core/constants/translation';
import { horizontalScale, verticalScale, ScaleFontSize } from '@/src/core/utils/scaling';
import { usePlanMutations } from '../hooks/usePlanMutations';
import { type DietCategory } from '../hooks/useDietCategories';

const { height: SCREEN_HEIGHT } = Dimensions.get('window');

const t = {
    editCategory: isRTL ? 'تعديل الفئة' : 'Edit Category',
    chooseIcon: isRTL ? 'اختر الأيقونة' : 'Choose Icon',
    categoryNameEn: isRTL ? 'اسم الفئة (بالإنجليزية)' : 'Category Name (English)',
    categoryNameAr: isRTL ? 'اسم الفئة (بالعربية)' : 'Category Name (Arabic)',
    description: isRTL ? 'الوصف' : 'Description',
    descriptionAr: isRTL ? 'الوصف (بالعربية)' : 'Description (Arabic)',
    enterCategoryName: isRTL ? 'أدخل اسم الفئة...' : 'Enter category name...',
    enterCategoryNameAr: 'أدخل اسم الفئة...',
    descriptionPlaceholder: isRTL ? 'وصف هذه الفئة الغذائية...' : 'Describe this diet category...',
    autoGenerateRanges: isRTL ? 'توليد النطاقات تلقائياً' : 'Auto-generate Ranges',
    autoGenerateDesc: isRTL ? 'توليد 14 نطاق تلقائيًا (1000-2500 كيلو كالوري)' : 'Auto-generate 14 ranges (1000-2500 kcal)',
    cancel: isRTL ? 'إلغاء' : 'Cancel',
    saveChanges: isRTL ? 'حفظ التغييرات' : 'Save Changes',
    saving: isRTL ? 'جاري الحفظ...' : 'Saving...',
    error: isRTL ? 'حدث خطأ' : 'Error occurred',
    updateSuccess: isRTL ? 'تم التحديث بنجاح' : 'Updated successfully',
};

const ICON_OPTIONS = ['🥗', '🥩', '🥑', '🧈', '🥬', '🏥', '⏰', '🩺', '🍳', '🥜', '🍎', '🥛'];

interface Props {
    visible: boolean;
    category: DietCategory | null;
    onClose: () => void;
    onSuccess?: () => void;
}

export default function EditMealCategories({ visible, category, onClose, onSuccess }: Props) {
    const [selectedEmoji, setSelectedEmoji] = useState('🥗');
    const [nameEn, setNameEn] = useState('');
    const [nameAr, setNameAr] = useState('');
    const [description, setDescription] = useState('');
    const [descriptionAr, setDescriptionAr] = useState('');
    const [autoGenerateRanges, setAutoGenerateRanges] = useState(false);

    const { updateDietCategory, isLoading, error } = usePlanMutations();

    // Initialize form with category data when modal opens
    useEffect(() => {
        if (category && visible) {
            setSelectedEmoji(category.emoji || '🥗');
            setNameEn(category.name || '');
            setNameAr(category.nameAr || '');
            setDescription(category.description || '');
            setDescriptionAr(category.descriptionAr || '');
            setAutoGenerateRanges(category.autoGenerateRanges || false);
        }
    }, [category, visible]);

    const resetForm = () => {
        setSelectedEmoji('🥗');
        setNameEn('');
        setNameAr('');
        setDescription('');
        setDescriptionAr('');
        setAutoGenerateRanges(false);
    };

    const handleSave = async () => {
        if (!category?._id) return;

        try {
            await updateDietCategory(category._id, {
                name: nameEn.trim(),
                nameAr: nameAr.trim() || undefined,
                emoji: selectedEmoji,
                description: description.trim() || undefined,
                autoGenerateRanges,
            });

            onSuccess?.();
            onClose();
        } catch (err) {
            console.error('Failed to update category:', err);
        }
    };

    const handleClose = () => {
        resetForm();
        onClose();
    };

    const isFormValid = nameEn.trim().length > 0 && !isLoading;
    const hasChanges = category && (
        nameEn !== category.name ||
        nameAr !== (category.nameAr || '') ||
        selectedEmoji !== category.emoji ||
        description !== (category.description || '') ||
        descriptionAr !== (category.descriptionAr || '') ||
        autoGenerateRanges !== category.autoGenerateRanges
    );

    return (
        <Modal visible={visible} animationType="slide" transparent onRequestClose={handleClose}>
            <View style={styles.overlay}>
                <View style={styles.modal}>
                    {/* Drag Handle */}
                    <View style={styles.handleContainer}>
                        <View style={styles.handle} />
                    </View>

                    {/* Header */}
                    <View style={[styles.header, { flexDirection: isRTL ? 'row' : 'row-reverse' }]}>
                        <Text style={styles.headerTitle}>{t.editCategory}</Text>
                        <TouchableOpacity style={styles.closeButton} onPress={handleClose}>
                            <X size={horizontalScale(24)} color={colors.textSecondary} />
                        </TouchableOpacity>
                    </View>

                    {/* Error Message */}
                    {error && (
                        <View style={styles.errorBanner}>
                            <Text style={styles.errorText}>{t.error}: {error.message}</Text>
                        </View>
                    )}

                    {/* Scrollable Content */}
                    <ScrollView
                        style={styles.content}
                        showsVerticalScrollIndicator={false}
                        contentContainerStyle={styles.contentContainer}
                    >
                        {/* Icon Selection */}
                        <View style={styles.section}>
                            <Text style={[styles.label, { textAlign: isRTL ? 'left' : 'right' }]}>
                                {t.chooseIcon}
                            </Text>
                            <View style={styles.iconGrid}>
                                {ICON_OPTIONS.map((emoji, index) => (
                                    <TouchableOpacity
                                        key={index}
                                        style={[
                                            styles.iconButton,
                                            selectedEmoji === emoji && styles.iconButtonActive,
                                        ]}
                                        onPress={() => setSelectedEmoji(emoji)}
                                    >
                                        <Text style={styles.iconEmoji}>{emoji}</Text>
                                    </TouchableOpacity>
                                ))}
                            </View>
                        </View>

                        {/* Form Fields */}
                        <View style={styles.formSection}>
                            {/* English Name */}
                            <View style={styles.inputGroup}>
                                <Text style={[styles.label, { textAlign: isRTL ? 'left' : 'right' }]}>
                                    {t.categoryNameEn}
                                </Text>
                                <TextInput
                                    style={[styles.input, { textAlign: isRTL ? 'right' : 'left' }]}
                                    placeholder={t.enterCategoryName}
                                    placeholderTextColor={colors.textSecondary}
                                    value={nameEn}
                                    onChangeText={setNameEn}
                                    editable={!isLoading}
                                />
                            </View>

                            {/* Arabic Name */}
                            <View style={styles.inputGroup}>
                                <Text style={[styles.label, { textAlign: isRTL ? 'left' : 'right' }]}>
                                    {t.categoryNameAr}
                                </Text>
                                <TextInput
                                    style={[styles.input, { textAlign: isRTL ? 'right' : 'left' }]}
                                    placeholder={t.enterCategoryNameAr}
                                    placeholderTextColor={colors.textSecondary}
                                    value={nameAr}
                                    onChangeText={setNameAr}
                                    editable={!isLoading}
                                />
                            </View>

                            {/* Description */}
                            <View style={styles.inputGroup}>
                                <Text style={[styles.label, { textAlign: isRTL ? 'left' : 'right' }]}>
                                    {t.description}
                                </Text>
                                <TextInput
                                    style={[styles.textArea, { textAlign: isRTL ? 'right' : 'left' }]}
                                    placeholder={t.descriptionPlaceholder}
                                    placeholderTextColor={colors.textSecondary}
                                    value={description}
                                    onChangeText={setDescription}
                                    multiline
                                    numberOfLines={3}
                                    textAlignVertical="top"
                                    editable={!isLoading}
                                />
                            </View>
                        </View>

                        {/* Toggle Switch Section */}
                        <View style={styles.toggleSection}>
                            <View style={[styles.toggleCard, { flexDirection: isRTL ? 'row' : 'row-reverse' }]}>
                                <View style={styles.toggleInfo}>
                                    <Text style={[styles.toggleTitle, { textAlign: isRTL ? 'left' : 'right' }]}>
                                        {t.autoGenerateRanges}
                                    </Text>
                                    <Text style={[styles.toggleSubtitle, { textAlign: isRTL ? 'left' : 'right' }]}>
                                        {t.autoGenerateDesc}
                                    </Text>
                                </View>
                                <Switch
                                    value={autoGenerateRanges}
                                    onValueChange={setAutoGenerateRanges}
                                    trackColor={{ false: '#E2E8F0', true: colors.primaryDark }}
                                    thumbColor="#FFFFFF"
                                    ios_backgroundColor="#E2E8F0"
                                    disabled={isLoading}
                                    style={{ transform: [{ rotate: '180deg' }] }}
                                />
                            </View>
                        </View>

                        {/* Spacer for scroll clearance */}
                        <View style={{ height: verticalScale(24) }} />
                    </ScrollView>

                    {/* Footer */}
                    <View style={[styles.footer, { flexDirection: isRTL ? 'row' : 'row-reverse' }]}>
                        <TouchableOpacity style={styles.cancelButton} onPress={handleClose} disabled={isLoading}>
                            <Text style={styles.cancelButtonText}>{t.cancel}</Text>
                        </TouchableOpacity>
                        <TouchableOpacity
                            style={styles.saveButtonWrapper}
                            onPress={handleSave}
                            disabled={!isFormValid || !hasChanges}
                            activeOpacity={0.9}
                        >
                            <LinearGradient
                                colors={isFormValid && hasChanges ? gradients.primary : ['#E1E8EF', '#E1E8EF']}
                                start={{ x: 0, y: 0 }}
                                end={{ x: 1, y: 0 }}
                                style={styles.saveButton}
                            >
                                {isLoading ? (
                                    <>
                                        <ActivityIndicator size="small" color="#FFFFFF" />
                                        <Text style={styles.saveButtonText}>{t.saving}</Text>
                                    </>
                                ) : (
                                    <>
                                        <Text style={[
                                            styles.saveButtonText,
                                            (!isFormValid || !hasChanges) && styles.saveButtonTextDisabled
                                        ]}>
                                            {t.saveChanges}
                                        </Text>
                                        <Save size={horizontalScale(20)} color={isFormValid && hasChanges ? '#FFFFFF' : colors.textSecondary} />
                                    </>
                                )}
                            </LinearGradient>
                        </TouchableOpacity>
                    </View>
                </View>
            </View>
        </Modal>
    );
}

const styles = StyleSheet.create({
    overlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.4)',
        justifyContent: 'flex-end',
    },
    modal: {
        backgroundColor: colors.bgPrimary,
        borderTopLeftRadius: horizontalScale(24),
        borderTopRightRadius: horizontalScale(24),
        height: SCREEN_HEIGHT * 0.85,
        flexDirection: 'column',
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.1,
        shadowRadius: 20,
        elevation: 10,
    },
    handleContainer: {
        alignItems: 'center',
        paddingTop: verticalScale(12),
        paddingBottom: verticalScale(8),
    },
    handle: {
        width: horizontalScale(40),
        height: verticalScale(6),
        backgroundColor: '#E2E8F0',
        borderRadius: horizontalScale(3),
    },
    // Header
    header: {
        paddingHorizontal: horizontalScale(20),
        paddingBottom: verticalScale(16),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    headerTitle: {
        fontSize: ScaleFontSize(18),
        fontWeight: '700',
        color: colors.textPrimary,
    },
    closeButton: {
        padding: horizontalScale(8),
        marginRight: horizontalScale(-8),
        borderRadius: horizontalScale(20),
    },
    // Error Banner
    errorBanner: {
        backgroundColor: '#FEE2E2',
        paddingHorizontal: horizontalScale(20),
        paddingVertical: verticalScale(12),
    },
    errorText: {
        fontSize: ScaleFontSize(14),
        color: '#DC2626',
        textAlign: 'center',
    },
    // Content
    content: {
        flex: 1,
    },
    contentContainer: {
        paddingHorizontal: horizontalScale(20),
        paddingTop: verticalScale(20),
    },
    section: {
        marginBottom: verticalScale(24),
    },
    label: {
        fontSize: ScaleFontSize(14),
        fontWeight: '500',
        color: colors.textSecondary,
        marginBottom: verticalScale(12),
    },
    // Icon Grid
    iconGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: horizontalScale(12),
    },
    iconButton: {
        width: horizontalScale(44),
        height: horizontalScale(44),
        borderRadius: horizontalScale(22),
        backgroundColor: colors.bgSecondary,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: 'transparent',
    },
    iconButtonActive: {
        backgroundColor: colors.bgPrimary,
        borderWidth: 2,
        borderColor: colors.primaryDark,
        shadowColor: '#5073FE',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 2,
    },
    iconEmoji: {
        fontSize: ScaleFontSize(20),
    },
    // Form
    formSection: {
        gap: verticalScale(16),
    },
    inputGroup: {
        marginBottom: verticalScale(4),
    },
    input: {
        height: verticalScale(44),
        backgroundColor: colors.bgSecondary,
        borderRadius: horizontalScale(12),
        paddingHorizontal: horizontalScale(16),
        fontSize: ScaleFontSize(16),
        color: colors.textPrimary,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 1,
    },
    textArea: {
        minHeight: verticalScale(88),
        backgroundColor: colors.bgSecondary,
        borderRadius: horizontalScale(12),
        paddingHorizontal: horizontalScale(16),
        paddingVertical: verticalScale(12),
        fontSize: ScaleFontSize(16),
        color: colors.textPrimary,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 1,
    },
    // Toggle Section
    toggleSection: {
        marginTop: verticalScale(24),
    },
    toggleCard: {
        padding: horizontalScale(16),
        backgroundColor: colors.bgSecondary,
        borderRadius: horizontalScale(16),
        borderWidth: 1,
        borderColor: colors.border,
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    toggleInfo: {
        flex: 1,
        paddingRight: horizontalScale(16),
    },
    toggleTitle: {
        fontSize: ScaleFontSize(14),
        fontWeight: '600',
        color: colors.textPrimary,
    },
    toggleSubtitle: {
        fontSize: ScaleFontSize(12),
        color: colors.textSecondary,
        marginTop: verticalScale(4),
    },
    // Footer
    footer: {
        paddingHorizontal: horizontalScale(20),
        paddingTop: verticalScale(16),
        paddingBottom: verticalScale(32),
        borderTopWidth: 1,
        borderTopColor: colors.border,
        gap: horizontalScale(16),
        backgroundColor: colors.bgPrimary,
    },
    cancelButton: {
        flex: 1,
        height: verticalScale(48),
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: horizontalScale(12),
    },
    cancelButtonText: {
        fontSize: ScaleFontSize(16),
        fontWeight: '500',
        color: colors.textSecondary,
    },
    saveButtonWrapper: {
        flex: 2,
        borderRadius: horizontalScale(12),
        overflow: 'hidden',
        shadowColor: '#5073FE',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 12,
        elevation: 4,
    },
    saveButton: {
        height: verticalScale(48),
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: horizontalScale(8),
    },
    saveButtonText: {
        fontSize: ScaleFontSize(16),
        fontWeight: '600',
        color: '#FFFFFF',
    },
    saveButtonTextDisabled: {
        color: colors.textSecondary,
    },
});
